### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tpalli** [Ericsson/ETCPACK#1]
Hi;
Are you planning on licensing this with more permissive license such as MIT?

If I understand correctly the current license seems to prohibit redistribution if any modifications (such as fixes, enhancements or 'glue code') are made which is a likely showstopper for projects using this code.

// Tapani

**Comment by jacobstrom-ericsson** [comment]
Hi Tapani,

No, we are not currently planning on issuing a different license. 

Best Regards,

-Jacob Ström
