### ISSUE TITLE
builded version?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [Ericsson/ETCPACK#14]
is there a version where it's already built? I want to decompress etc.dds files but I don't have coding experience at all :(

**Comment by jacobstrom-ericsson** [comment]
Unfortunately there is no already built version. If you are on macOS, there is a step-by-step instruction on how to compile it in the answer to issue #13, which you can find [here](https://github.com/Ericsson/ETCPACK/issues/13):

**Comment by umustbeloggedintododat** [comment]
I don't need it anyways since I fixed my problem [here](https://forum.xentax.com/viewtopic.php?f=16&t=22818&p=167675#p167675)
