### ISSUE TITLE
imconv is a very poor default

### ISSUE THREAD

**Issue by boblaublaw** [Ericsson/ETCPACK#2]
First, is this project active? I see a recent change four months ago.

However, upon trying your etcpack.exe I encountered and error because my Windows 10 system does not have "imconv".  I investigated further and learned that imconv is an image conversion tool which was last updated in 1995.  I had to dig quite a bit to find the source for this tool as many links from 1995 do not work.

ftp://ftp.sdsc.edu/pub/sdsc/graphics/imtools/source/

Given that this tool has not been updated in over 20 years, and ImageMagick was updated yesterday, perhaps the etcpack source could be updated to reflect a modern image conversion tool?  Presumably, this would save many people, myself included, the hassle of having to make the change themself and rebuild from source.

**Comment by jacobstrom-ericsson** [comment]
Hi, 

Actually it is ImageMagick that we use. The executable was renamed "imconv" instead of "convim" (which I believe is what ImageMagick uses) for reasons that I don't remember. So making a copy of your ImageMagick file "convim.exe" to "imconv.exe" will do the trick.

Best Regards,

-Jacob
